# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-04 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbyuser',
            name='created_at',
        ),
    ]
