# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_jobbyuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbyuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
